import { reddit } from '@devvit/web/server';
import { createDevvitTest } from '@devvit/test/server/vitest';
import type { ConversationData } from '@devvit/web/server';
import type { OnModMailRequest } from '@devvit/web/shared';
import { describe, expect, vi } from 'vitest';

import { DEFAULT_SETTINGS, REQUIRED_APPEAL_FIELDS, type AppealCase } from '../../shared/appeals';
import { saveCase } from './store';
import { buildInternalNote, handleModmailEvent, runAppealAction } from './modmail';

const baseCase: AppealCase = {
  id: 'case-1',
  subredditId: 't5_appealdesq',
  subredditName: 'appealdesq_dev',
  conversationId: 'conversation-1',
  userName: 'appealer',
  subject: 'Ban appeal',
  status: 'awaiting_user',
  score: 0,
  missingFields: [],
  summary: 'Appeal template sent. Waiting for structured details.',
  lastMessagePreview: 'unban me',
  followupCount: 0,
  createdAt: 1,
  updatedAt: 1,
};

function modmailRequest(conversationId: string, messageId: string): OnModMailRequest {
  return {
    type: 'ModMail',
    messageAuthorType: 'participant_user',
    conversationState: 'new',
    conversationType: 'sr_user',
    isAutoGenerated: false,
    conversationId,
    messageId,
  };
}

function conversationWithUserMessage({
  conversationId,
  messageId,
  subject,
  body,
}: {
  conversationId: string;
  messageId: string;
  subject: string;
  body: string;
}): ConversationData {
  return {
    id: conversationId,
    subject,
    conversationType: 'sr_user',
    isAuto: false,
    participant: {
      name: 'appealer',
      isMod: false,
      isParticipant: true,
    },
    authors: [
      {
        name: 'appealer',
        isMod: false,
        isParticipant: true,
      },
    ],
    messages: {
      [messageId]: {
        id: messageId,
        body,
        bodyMarkdown: body,
        date: '2026-06-11T09:00:00.000Z',
        isInternal: false,
        author: {
          name: 'appealer',
          isMod: false,
          isParticipant: true,
        },
      },
    },
    modActions: {},
  };
}

describe('AppealDesq modmail notes', () => {
  const test = createDevvitTest({
    subredditName: 'appealdesq_dev',
    subredditId: 't5_appealdesq',
    username: 'mod-tester',
  });

  test('falls back to required field bullets when stored missing fields are stale', () => {
    const note = buildInternalNote(baseCase);

    expect(note).not.toContain('Missing fields: None');
    for (const field of REQUIRED_APPEAL_FIELDS) {
      expect(note).toContain(`- ${field}`);
    }
  });

  test('only displays no missing fields for a complete score', () => {
    const note = buildInternalNote({
      ...baseCase,
      status: 'ready_for_review',
      score: 5,
      missingFields: [],
    });

    expect(note).toContain('Completeness score: 5/5');
    expect(note).toContain('Missing fields: None');
  });

  test('uses muted pause recommendation in internal notes', () => {
    const note = buildInternalNote({
      ...baseCase,
      status: 'paused_muted',
      summary: 'Appeal paused: user may be muted. User is currently muted in modmail.',
    });

    expect(note).toContain('AppealDesq status: paused_muted');
    expect(note).toContain('Recommended next action: Wait for mute to expire or review manually.');
  });

  test('simulates initial modmail handling without sending contradictory notes', async ({
    mocks,
  }) => {
    await mocks.redis.clear();
    const conversationId = 'conversation-live-initial';
    const conversation = conversationWithUserMessage({
      conversationId,
      messageId: 'message-1',
      subject: 'Ban appeal',
      body: 'unban me',
    });
    const replies: Array<Parameters<typeof reddit.modMail.reply>[0]> = [];

    vi.spyOn(reddit.modMail, 'getConversation').mockResolvedValue({
      conversation,
      user: {
        id: 't2_appealer',
        name: 'appealer',
        recentComments: {},
        recentPosts: {},
        recentConvos: {},
      },
    });
    vi.spyOn(reddit.modMail, 'reply').mockImplementation(async (params) => {
      replies.push(params);
      return { conversation };
    });

    const result = await handleModmailEvent(modmailRequest(conversationId, 'message-1'));
    const internalNote = replies.find((reply) => reply.isInternal)?.body ?? '';

    expect(result.status).toBe('created');
    expect(replies).toHaveLength(2);
    expect(internalNote).toContain('Completeness score: 1/5');
    expect(internalNote).not.toContain('Missing fields: None');
    expect(internalNote).not.toContain('No required fields are missing');
    expect(internalNote).toContain('- Post/comment link, or clear statement that no link applies');
    expect(internalNote).toContain('- Reason the mod team should reconsider');
  });

  test('simulates muted initial modmail as paused without a public follow-up', async ({ mocks }) => {
    await mocks.redis.clear();
    const conversationId = 'conversation-muted-initial';
    const conversation = conversationWithUserMessage({
      conversationId,
      messageId: 'message-1',
      subject: 'Ban appeal',
      body: 'why was i banned',
    });
    const replies: Array<Parameters<typeof reddit.modMail.reply>[0]> = [];

    vi.spyOn(reddit.modMail, 'getConversation').mockResolvedValue({
      conversation,
      user: {
        id: 't2_appealer',
        name: 'appealer',
        recentComments: {},
        recentPosts: {},
        recentConvos: {},
        muteStatus: {
          isMuted: true,
          muteCount: 1,
        },
      },
    });
    vi.spyOn(reddit.modMail, 'reply').mockImplementation(async (params) => {
      replies.push(params);
      return { conversation };
    });

    const result = await handleModmailEvent(modmailRequest(conversationId, 'message-1'));
    const internalNote = replies.find((reply) => reply.isInternal)?.body ?? '';

    expect(result.status).toBe('created');
    const appealCase = 'case' in result ? result.case : undefined;
    if (!appealCase) {
      throw new Error('Expected created case');
    }
    expect(appealCase.status).toBe('paused_muted');
    expect(appealCase.summary).toContain('Appeal paused: user may be muted');
    expect(replies).toHaveLength(1);
    expect(replies[0]?.isInternal).toBe(true);
    expect(internalNote).toContain('Recommended next action: Wait for mute to expire or review manually.');
    expect(internalNote).not.toContain('Ask for the missing fields before spending review time.');
  });

  test('simulates non-repliable modmail as paused', async ({ mocks }) => {
    await mocks.redis.clear();
    const conversationId = 'conversation-not-repliable';
    const conversation = {
      ...conversationWithUserMessage({
        conversationId,
        messageId: 'message-1',
        subject: 'Ban appeal',
        body: 'why was i banned',
      }),
      isRepliable: false,
    };
    const replies: Array<Parameters<typeof reddit.modMail.reply>[0]> = [];

    vi.spyOn(reddit.modMail, 'getConversation').mockResolvedValue({
      conversation,
      user: {
        id: 't2_appealer',
        name: 'appealer',
        recentComments: {},
        recentPosts: {},
        recentConvos: {},
      },
    });
    vi.spyOn(reddit.modMail, 'reply').mockImplementation(async (params) => {
      replies.push(params);
      return { conversation };
    });

    const result = await handleModmailEvent(modmailRequest(conversationId, 'message-1'));

    expect(result.status).toBe('created');
    const appealCase = 'case' in result ? result.case : undefined;
    if (!appealCase) {
      throw new Error('Expected created case');
    }
    expect(appealCase.status).toBe('paused_muted');
    expect(appealCase.summary).toContain('Modmail conversation is not currently repliable.');
    expect(replies).toHaveLength(1);
    expect(replies[0]?.isInternal).toBe(true);
  });

  test('simulates follow-up from stale stored missing fields using the latest message', async ({
    mocks,
  }) => {
    await mocks.redis.clear();
    const conversationId = 'conversation-live-followup';
    const conversation = conversationWithUserMessage({
      conversationId,
      messageId: 'message-1',
      subject: 'Ban appeal',
      body: 'why was i banned',
    });
    const replies: Array<Parameters<typeof reddit.modMail.reply>[0]> = [];
    const staleCase: AppealCase = {
      ...baseCase,
      id: 'stale-case',
      conversationId,
      score: 0,
      missingFields: [],
      followupCount: 0,
    };

    await saveCase(staleCase, DEFAULT_SETTINGS);
    vi.spyOn(reddit.modMail, 'getConversation').mockResolvedValue({
      conversation,
      user: {
        id: 't2_appealer',
        name: 'appealer',
        recentComments: {},
        recentPosts: {},
        recentConvos: {},
      },
    });
    vi.spyOn(reddit.modMail, 'reply').mockImplementation(async (params) => {
      replies.push(params);
      return { conversation };
    });

    const result = await runAppealAction('stale-case', 'ask_followup');
    const followup = replies.at(0)?.body ?? '';

    expect(result.ok).toBe(true);
    expect(result.case.score).toBe(1);
    expect(result.case.missingFields).toHaveLength(4);
    expect(followup).toContain('The appeal is still missing some required information');
    expect(followup).not.toContain('No required fields are missing');
    expect(followup).toContain('- Post/comment link, or clear statement that no link applies');
    expect(followup).toContain('- Reason the mod team should reconsider');
  });

  test('simulates muted follow-up as blocked and paused with no outbound reply', async ({ mocks }) => {
    await mocks.redis.clear();
    const conversationId = 'conversation-muted-followup';
    const conversation = conversationWithUserMessage({
      conversationId,
      messageId: 'message-1',
      subject: 'Ban appeal',
      body: 'why was i banned',
    });
    const replies: Array<Parameters<typeof reddit.modMail.reply>[0]> = [];
    const staleCase: AppealCase = {
      ...baseCase,
      id: 'muted-case',
      conversationId,
      score: 0,
      missingFields: [],
      followupCount: 0,
    };

    await saveCase(staleCase, DEFAULT_SETTINGS);
    vi.spyOn(reddit.modMail, 'getConversation').mockResolvedValue({
      conversation,
      user: {
        id: 't2_appealer',
        name: 'appealer',
        recentComments: {},
        recentPosts: {},
        recentConvos: {},
        muteStatus: {
          isMuted: true,
          muteCount: 1,
        },
      },
    });
    vi.spyOn(reddit.modMail, 'reply').mockImplementation(async (params) => {
      replies.push(params);
      return { conversation };
    });

    const result = await runAppealAction('muted-case', 'ask_followup');

    expect(result.ok).toBe(false);
    expect(result.case.status).toBe('paused_muted');
    expect(result.message).toBe('Follow-up disabled. Appeal paused: user may be muted.');
    expect(replies).toEqual([]);
  });
});
